name: Build User Config

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Setup ZMK
        run: |
          git clone --branch main https://github.com/zmkfirmware/zmk.git zmk
          cd zmk
          west init -l app
          west update
          pip install -r scripts/requirements.txt

      - name: Build Left Half
        run: |
          cd zmk
          west build -s app -b k03h -- -DZMK_CONFIG=$GITHUB_WORKSPACE/config -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE

      - name: Build Right Half
        run: |
          cd zmk
          west build -s app -b k03h -- -DZMK_CONFIG=$GITHUB_WORKSPACE/config -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE -DOVERLAY=$GITHUB_WORKSPACE/k03h_right.dts

