---
include:
  - board: k03
    cmake-args: -DOVERLAY_CONFIG=boards/arm/k03/k03_left.overlay
    artifact-name: k03_left

  - board: k03
    cmake-args: -DOVERLAY_CONFIG=boards/arm/k03/k03_right.overlay
    artifact-name: k03_right

